### PR TITLE
📚 DOCS: typo fix

### PR DESCRIPTION
**Pull request by akhmerov**

### CODE REVIEW

**Comment by choldgraf** [comment]
Reopening to trigger the rtd build again

**Comment by choldgraf** [comment]
Hmmm - it looks like RTD is throwing a warning on this line:

```
/home/docs/checkouts/readthedocs.org/user_builds/jupyter-cache/checkouts/61/docs/using/api.ipynb:30002: WARNING: Unknown interpreted text role "jupyter-download:notebook".
```

I can't remember but is the `jupyter-download` role from `jupyter-sphinx`? Maybe we just need to either add that dependency or remove that role?

**Comment by akhmerov** [comment]
Your memory is correct.

**Comment by choldgraf** [comment]
hmm - well if we're *only* using that one role and no other jupyter-sphinx functionality, then my inclination is to remove the use of the role. WDYT?

**Comment by chrisjsewell** [comment]
This has been removed from myst-nb and the `nb-download` role should now be used

**Comment by chrisjsewell** [comment]
cheers

**Pull request merged**
