### PR TITLE
UPDATE: SQLAlchemy 2.0

### PR DESCRIPTION
**Pull request by jzluo**
As mentioned in #92, SQLAlchemy is pinned to <1.5. All tests pass with SQLAlchemy 2.0.6 - the only SQLAlchemy warning is:
```python
jupyter_cache/cache/db.py:17
  /home/jon/projects/jupyter-cache/jupyter_cache/cache/db.py:17: MovedIn20Warning: The ``declarative_base()`` 
function is now available as sqlalchemy.orm.declarative_base(). (deprecated since: 1.4) (Background on 
SQLAlchemy 2.0 at: https://sqlalche.me/e/b8d9)
    OrmBase = declarative_base()
```
because of https://docs.sqlalchemy.org/en/20/changelog/migration_14.html#change-5508. [`sqlalchemy.ext.declarative.declarative_base` is still present.](https://github.com/sqlalchemy/sqlalchemy/blob/d9539e3990acf19ee1a03690d4a7441d26a7fbfd/lib/sqlalchemy/ext/declarative/__init__.py#L26-L27)

### CODE REVIEW

**Comment by jzluo** [comment]
@choldgraf apologies for the ping - I saw that you were the reviewer for a similar PR about SQLAlchemy 1.4. Do you have an estimate for when someone can check this PR or create a different solution? Currently projects can't use myst-nb and SQLAlchemy 2.

**Comment by jzluo** [comment]
@chrisjsewell could we get eyes on this? Thank you

**Review by choldgraf — DISMISSED** [review]
LGTM as long as the tests are happy 👍 . Does sqalchemy often make breaking changes at minor versions? If not, then why not pin it to `<3.0`?

**Comment by jzluo** [comment]
@choldgraf @chrisjsewell sorry for the ping again - I think it's important to resolve this quickly as it prevents projects that use myst-nb from using sqlalchemy 2.0.

**Comment by choldgraf** [comment]
I'll try to take a look this weekend if I have a moment. In the meantime it'd be helpful if you made the modifications to the codebase to avoid the new warning that pops up. Not crucial but it'd be helpful since we'll need to do that at some point anyway

**Review by choldgraf — APPROVED** [review]
LGTM thanks! Appreciate the extra fix to get rid of the warning 👍

**Comment by jzluo** [comment]
Thank you Chris!

**Comment by DimitriPapadopoulos** [comment]
Updating `jupyter_cache` from 0.5.0 to 0.6.0 breaks the “**stable (ubuntu-latest, 3.8, pip, doc)**” CI test of [bids-standard/pybids](https://github.com/bids-standard/pybids) with:
```
ImportError: cannot import name 'declarative_base' from 'sqlalchemy.orm' (/home/runner/work/pybids/pybids/virtenv/lib/python3.8/site-packages/sqlalchemy/orm/__init__.py)
```
See https://github.com/bids-standard/pybids/actions/runs/4767649000/jobs/8476115124

It is unclear from the logs which version of SQLAlchemy we use. Most probably [python3-sqlalchemy 1.4.31](https://packages.ubuntu.com/jammy/python3-sqlalchemy).

**Comment by choldgraf** [comment]
Ah i bet you're using old version of sqlalchemy. We could have used a try/except block for the import instead of just changing it. If somebody wants to make a quick PR (@jzluo ?) Im happy to review and cut a quick patch release

**Comment by DimitriPapadopoulos** [comment]
You're correct, from [pybids/pyproject.toml](https://github.com/bids-standard/pybids/blob/63c2dcee1c80d1cc8bb703c00a03cc7fb2ccc846/pyproject.toml#L32):
```
  "sqlalchemy <1.4.0.dev0",
```
Perhaps we should update. I'll look into why we need SQLAlchemy < 1.4.0.

**Comment by DimitriPapadopoulos** [comment]
In the meantime, see PR #105 for compatibility with SQLAlchemy 1.3.

**Pull request merged**
